# Generated by Django 3.2.8 on 2021-10-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_added', '0002_blogpost_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
